import 'package:iris/features/meta_settings/model/enum/settings_section.dart';
import 'package:iris/features/meta_settings/model/enum/setting_value_type.dart';
import 'package:iris/features/meta_settings/model/enum/setting_widget_kind.dart';
import 'package:iris/features/meta_settings/model/setting_def.dart';

/// 副音播放 (background playback) meta settings rows (`background_playback.*`).
///
/// All rows are `custom` with hand-written editor bindings (see
/// EditorBindings): their values live in the background playback store, NOT in
/// the `app.` snapshot, so the generic toggle/enum renderers (hardwired to
/// `app.` fields) cannot drive them. Visibility is gated by
/// `DefVisibility.registerPrefix('background_playback.', ...)` in app_startup:
/// the rows only exist when [BackgroundPlaybackGate] is enabled (meta era).
abstract final class BackgroundPlaybackSettingsContribution {
  static const String groupHeaderKey = 'group_background_playback';

  static List<SettingDef> get defs =>       const [
        // 开机状态: arm the 副音 run (on, stopped) at launch. Independent of
        // the group-leading keepWarmPlayer row below (that one only holds an
        // idle engine while the run is OFF).
        SettingDef(
          key: 'background_playback.startArmed',
          section: SettingsSection.play,
          valueType: SettingValueType.bool,
          defaultValue: 'true',
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_start_armed',
          titleKey: 'set_bg_start_armed',
          subtitleKey: 'set_bg_start_armed_desc',
          iconKey: 'bg_start_armed',
          sortOrder: 68,
        ),
        // Group leader (exactly one row carries the group header — see
        // settings_section_order_test).
        SettingDef(
          key: 'background_playback.keepWarmPlayer',
          section: SettingsSection.play,
          valueType: SettingValueType.bool,
          defaultValue: 'true',
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_keep_warm',
          titleKey: 'set_bg_keep_warm',
          subtitleKey: 'set_bg_keep_warm_desc',
          iconKey: 'bg_keep_warm',
          groupHeaderKey: groupHeaderKey,
          sortOrder: 67,
        ),
        SettingDef(
          key: 'background_playback.sourceManage',
          section: SettingsSection.play,
          valueType: SettingValueType.json,
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_sources',
          titleKey: 'set_bg_sources',
          subtitleKey: 'set_bg_sources_desc',
          iconKey: 'bg_sources',
          sortOrder: 70,
        ),
        SettingDef(
          key: 'background_playback.fallbackBanner',
          section: SettingsSection.play,
          valueType: SettingValueType.bool,
          defaultValue: 'true',
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_fallback_banner',
          titleKey: 'set_bg_fallback_banner',
          subtitleKey: 'set_bg_fallback_banner_desc',
          iconKey: 'bg_fallback_banner',
          sortOrder: 97,
        ),
        SettingDef(
          key: 'background_playback.followFgSwitch',
          section: SettingsSection.play,
          valueType: SettingValueType.bool,
          defaultValue: 'false',
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_follow_fg_switch',
          titleKey: 'set_bg_follow_fg',
          subtitleKey: 'set_bg_follow_fg_desc',
          iconKey: 'bg_follow_fg',
          sortOrder: 71,
        ),
        SettingDef(
          key: 'background_playback.allowSameFile',
          section: SettingsSection.play,
          valueType: SettingValueType.bool,
          defaultValue: 'false',
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_allow_same_file',
          titleKey: 'set_bg_allow_same_file',
          subtitleKey: 'set_bg_allow_same_file_desc',
          iconKey: 'bg_allow_same_file',
          sortOrder: 72,
        ),
        SettingDef(
          key: 'background_playback.rateLock',
          section: SettingsSection.play,
          valueType: SettingValueType.bool,
          defaultValue: 'true',
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_rate_lock',
          titleKey: 'set_bg_rate_lock',
          subtitleKey: 'set_bg_rate_lock_desc',
          iconKey: 'bg_rate_lock',
          sortOrder: 73,
        ),
        SettingDef(
          key: 'background_playback.videoLayout',
          section: SettingsSection.play,
          valueType: SettingValueType.enumeration,
          defaultValue: 'fullscreen',
          enumValues: ['fullscreen', 'pip', 'split'],
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_video_layout',
          titleKey: 'set_bg_video_layout',
          subtitleKey: 'set_bg_video_layout_desc',
          iconKey: 'bg_video_layout',
          sortOrder: 74,
        ),
        SettingDef(
          key: 'background_playback.alignDefault',
          section: SettingsSection.play,
          valueType: SettingValueType.enumeration,
          defaultValue: 'fgHead',
          enumValues: ['fgHead', 'fgPosition', 'bgPercent'],
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_align_default',
          titleKey: 'set_bg_align_default',
          subtitleKey: 'set_bg_align_default_desc',
          iconKey: 'bg_align_default',
          sortOrder: 75,
        ),
        SettingDef(
          key: 'background_playback.ratioExplicitSave',
          section: SettingsSection.play,
          valueType: SettingValueType.bool,
          defaultValue: 'true',
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_ratio_explicit_save',
          titleKey: 'set_bg_ratio_explicit_save',
          subtitleKey: 'set_bg_ratio_explicit_save_desc',
          iconKey: 'bg_ratio_explicit_save',
          sortOrder: 76,
        ),
        SettingDef(
          key: 'background_playback.autoFocusControl',
          section: SettingsSection.play,
          valueType: SettingValueType.bool,
          defaultValue: 'true',
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_auto_focus_control',
          titleKey: 'set_bg_auto_focus',
          subtitleKey: 'set_bg_auto_focus_desc',
          iconKey: 'bg_auto_focus',
          sortOrder: 69,
        ),
        SettingDef(
          key: 'background_playback.seekLink',
          section: SettingsSection.play,
          valueType: SettingValueType.enumeration,
          defaultValue: 'linked',
          enumValues: ['linked', 'independent'],
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_seek_link',
          titleKey: 'set_bg_seek_link',
          subtitleKey: 'set_bg_seek_link_desc',
          iconKey: 'bg_seek_link',
          sortOrder: 77,
        ),
        // 副音 button stop behavior: what the quick-bar gate (and the bg stop
        // button) does on close — pause the media (re-align next time) or unload
        // it (reload next time). The run and warm engine always survive.
        SettingDef(
          key: 'background_playback.gateStopBehavior',
          section: SettingsSection.play,
          valueType: SettingValueType.enumeration,
          defaultValue: 'pause',
          enumValues: ['pause', 'unload'],
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_gate_stop_behavior',
          titleKey: 'set_bg_gate_stop_behavior',
          subtitleKey: 'set_bg_gate_stop_behavior_desc',
          iconKey: 'bg_gate_stop_behavior',
          sortOrder: 84,
        ),
        SettingDef(
          key: 'background_playback.useSavedMapping',
          section: SettingsSection.play,
          valueType: SettingValueType.bool,
          defaultValue: 'true',
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_use_saved_mapping',
          titleKey: 'set_bg_use_saved_mapping',
          subtitleKey: 'set_bg_use_saved_mapping_desc',
          iconKey: 'bg_use_saved_mapping',
          sortOrder: 89,
        ),
        SettingDef(
          key: 'background_playback.lockLevel',
          section: SettingsSection.play,
          valueType: SettingValueType.enumeration,
          defaultValue: 'high',
          enumValues: ['high', 'low'],
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_lock_level',
          titleKey: 'set_bg_lock_level',
          subtitleKey: 'set_bg_lock_level_desc',
          iconKey: 'bg_lock_level',
          sortOrder: 90,
        ),
        SettingDef(
          key: 'background_playback.stepMode',
          section: SettingsSection.play,
          valueType: SettingValueType.enumeration,
          defaultValue: 'swapOnly',
          enumValues: ['swapOnly', 'followLink'],
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_step_mode',
          titleKey: 'set_bg_step_mode',
          subtitleKey: 'set_bg_step_mode_desc',
          iconKey: 'bg_step_mode',
          sortOrder: 92,
        ),
        SettingDef(
          key: 'background_playback.alignAutoPauseRemainSec',
          section: SettingsSection.play,
          valueType: SettingValueType.int,
          defaultValue: '5',
          clampMin: 1,
          clampMax: 120,
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_align_warn',
          titleKey: 'set_bg_align_warn',
          subtitleKey: 'set_bg_align_warn_desc',
          iconKey: 'bg_align_warn',
          sortOrder: 96,
        ),
        SettingDef(
          key: 'background_playback.exhaustedAction',
          section: SettingsSection.play,
          valueType: SettingValueType.enumeration,
          defaultValue: 'nextBg',
          enumValues: ['nextBg', 'stopRestoreFg'],
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_exhausted_action',
          titleKey: 'set_bg_exhausted_action',
          subtitleKey: 'set_bg_exhausted_action_desc',
          iconKey: 'bg_exhausted_action',
          sortOrder: 98,
        ),
        // Physical minimum length of an A–B mapping segment (ms).
        SettingDef(
          key: 'background_playback.minSegmentSpanMs',
          section: SettingsSection.play,
          valueType: SettingValueType.int,
          defaultValue: '500',
          clampMin: 100,
          clampMax: 5000,
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_min_segment_span',
          titleKey: 'set_bg_min_segment_span',
          subtitleKey: 'set_bg_min_segment_span_desc',
          iconKey: 'bg_min_segment_span',
          sortOrder: 80,
        ),
        // P-handle boundary behaviour after a reverse drag.
        SettingDef(
          key: 'background_playback.pAlignKeepMaxLength',
          section: SettingsSection.play,
          valueType: SettingValueType.bool,
          defaultValue: 'true',
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_p_align_keep_length',
          titleKey: 'set_bg_p_align_keep_length',
          subtitleKey: 'set_bg_p_align_keep_length_desc',
          iconKey: 'bg_p_align_keep_length',
          sortOrder: 81,
        ),
        // Which handles spend a bundled pile before translating (P pull-away
        // and/or an A/B outward drag).
        SettingDef(
          key: 'background_playback.stickyConsume',
          section: SettingsSection.play,
          valueType: SettingValueType.enumeration,
          defaultValue: 'all',
          enumValues: ['off', 'pOnly', 'abOnly', 'all'],
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_sticky_consume',
          titleKey: 'set_bg_sticky_consume',
          subtitleKey: 'set_bg_sticky_consume_desc',
          iconKey: 'bg_sticky_consume',
          sortOrder: 82,
        ),
        // APB fg 显示窗口倍率: when the foreground is much longer than the 副音
        // file, the align editor shows only `zoom × bgDur` of fg so the A–B
        // mapping does not collapse to a near-point. 1.0 disables the zoom.
        SettingDef(
          key: 'background_playback.fgWindowZoom',
          section: SettingsSection.play,
          valueType: SettingValueType.double,
          defaultValue: '2.0',
          clampMin: 1.0,
          clampMax: 10.0,
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_fg_window_zoom',
          titleKey: 'set_bg_fg_window_zoom',
          subtitleKey: 'set_bg_fg_window_zoom_desc',
          iconKey: 'bg_fg_window_zoom',
          sortOrder: 85,
        ),
        // Whether the q handle pushes the mapping (modifies the alignment) once
        // A/B reach 12/11 o'clock, instead of clamping the pan at the boundary.
        SettingDef(
          key: 'background_playback.fgWindowPushBg',
          section: SettingsSection.play,
          valueType: SettingValueType.bool,
          defaultValue: 'false',
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_fg_window_push_bg',
          titleKey: 'set_bg_fg_window_push_bg',
          subtitleKey: 'set_bg_fg_window_push_bg_desc',
          iconKey: 'bg_fg_window_push_bg',
          sortOrder: 86,
        ),
        // Snap-to-saved-boundary (卡值）: A / P / B stop exactly at saved
        // segment boundaries like at the 0% / 100% ends. Walls are temporary
        // (a hit gesture releases for the next one); the toggle resets them.
        SettingDef(
          key: 'background_playback.snapEnabled',
          section: SettingsSection.play,
          valueType: SettingValueType.bool,
          defaultValue: 'false',
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_align_snap',
          titleKey: 'set_bg_align_snap',
          subtitleKey: 'set_bg_align_snap_desc',
          iconKey: 'bg_align_snap',
          sortOrder: 87,
        ),
        // How many recently released snap walls stay passable. Hitting a new
        // wall cancels the oldest release when full (1–10000, default 1).
        SettingDef(
          key: 'background_playback.snapReleaseLimit',
          section: SettingsSection.play,
          valueType: SettingValueType.int,
          defaultValue: '1',
          clampMin: 1,
          clampMax: 10000,
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_align_snap_release_limit',
          titleKey: 'set_bg_align_snap_release_limit',
          subtitleKey: 'set_bg_align_snap_release_limit_desc',
          iconKey: 'bg_align_snap_release_limit',
          sortOrder: 88,
        ),
        // Informational row: opens the A/P/B guide dialog.
        SettingDef(
          key: 'background_playback.segmentGuide',
          section: SettingsSection.play,
          valueType: SettingValueType.json,
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_segment_guide',
          titleKey: 'set_bg_segment_guide',
          subtitleKey: 'set_bg_segment_guide_desc',
          iconKey: 'bg_segment_guide',
          sortOrder: 83,
        ),
        SettingDef(
          key: 'background_playback.alignRingAssignment',
          section: SettingsSection.play,
          valueType: SettingValueType.enumeration,
          // Default: foreground on the OUTER ring, so the APB handles (drawn on
          // the bg ring) sit on the inner one.
          defaultValue: 'fgOuter',
          enumValues: ['fgInner', 'fgOuter'],
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_align_ring',
          titleKey: 'set_bg_align_ring',
          subtitleKey: 'set_bg_align_ring_desc',
          iconKey: 'bg_align_ring',
          sortOrder: 91,
        ),
        SettingDef(
          key: 'background_playback.quickBar',
          section: SettingsSection.play,
          valueType: SettingValueType.bool,
          defaultValue: 'true',
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_quick_bar',
          titleKey: 'set_bg_quick_bar',
          subtitleKey: 'set_bg_quick_bar_desc',
          iconKey: 'bg_quick_bar',
          sortOrder: 78,
        ),
        SettingDef(
          key: 'background_playback.quickBarAlign',
          section: SettingsSection.play,
          valueType: SettingValueType.enumeration,
          defaultValue: 'right',
          enumValues: ['left', 'right'],
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_quick_bar_align',
          titleKey: 'set_bg_quick_bar_align',
          subtitleKey: 'set_bg_quick_bar_align_desc',
          iconKey: 'bg_quick_bar_align',
          sortOrder: 79,
        ),
        SettingDef(
          key: 'background_playback.itemSwitch',
          section: SettingsSection.play,
          valueType: SettingValueType.enumeration,
          defaultValue: 'newBg',
          enumValues: ['keepPlaying', 'newBg'],
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_item_switch',
          titleKey: 'set_bg_item_switch',
          subtitleKey: 'set_bg_item_switch_desc',
          iconKey: 'bg_item_switch',
          sortOrder: 94,
        ),
        SettingDef(
          key: 'background_playback.segmentSwitch',
          section: SettingsSection.play,
          valueType: SettingValueType.enumeration,
          defaultValue: 'keepPlaying',
          enumValues: ['keepPlaying', 'newBg'],
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_segment_switch',
          titleKey: 'set_bg_segment_switch',
          subtitleKey: 'set_bg_segment_switch_desc',
          iconKey: 'bg_segment_switch',
          sortOrder: 95,
        ),
        SettingDef(
          key: 'background_playback.vmScopeMode',
          section: SettingsSection.play,
          valueType: SettingValueType.enumeration,
          defaultValue: 'perBlock',
          enumValues: ['perBlock', 'wholeVirtual'],
          widgetKind: SettingWidgetKind.custom,
          editorKey: 'bg_vm_scope_mode',
          titleKey: 'set_bg_vm_scope_mode',
          subtitleKey: 'set_bg_vm_scope_mode_desc',
          iconKey: 'bg_vm_scope_mode',
          sortOrder: 93,
        ),
      ];
}
